export const TASK_ASSIGNED = 'ASSIGNED'
export const TASK_IN_PROCESS = 'IN PROCESS'
export const TASK_FINISHED = 'FINISHED'
export const FIGURE = 'Figure'
export const SUBFIGURE = 'Subfigure'
export const FIGURE_TO_REVIEW = 'To Review'
export const FIGURE_REVIEWED = 'Reviewed'
export const FIGURE_SKIPPED = 'Skipped'
