name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.1]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm 7
      run: npm i -g npm@7.5.4 --registry=https://registry.npmjs.org              
    - name: Install Packages
      run: npm install
      env:
        npm_config_user: "root"
    - name: Build page
      run: npm run build
    - name: SCP build folder
      uses: appleboy/scp-action@master
      with:
        host: ${{secrets.HOST}}      
        port: ${{secrets.PORT}}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PASSWORD }}
        source: "./build/*"
        target: ${{secrets.PATH}}    
